"""add gallery_images column

Revision ID: 1c335a1f6a70
Revises: bae40da64f45
Create Date: 2026-06-21 12:36:16.396245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c335a1f6a70'
down_revision: Union[str, Sequence[str], None] = 'bae40da64f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gallery_images', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'gallery_images')
    # ### end Alembic commands ###
