"""add sales orders

Revision ID: bae40da64f45
Revises: 6c86ff85edec
Create Date: 2026-06-13 18:49:51.005389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae40da64f45'
down_revision: Union[str, Sequence[str], None] = '6c86ff85edec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('broker', sa.String(), nullable=True),
    sa.Column('order_no', sa.Integer(), nullable=True),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('catalog', sa.String(), nullable=True),
    sa.Column('vol', sa.String(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('packing', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('order_pcs', sa.Integer(), nullable=True),
    sa.Column('disp_pcs', sa.Integer(), nullable=True),
    sa.Column('bal_pcs', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('over_due_days', sa.Integer(), nullable=True),
    sa.Column('due_days', sa.Integer(), nullable=True),
    sa.Column('sales_man', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_customer_name'), 'sales_orders', ['customer_name'], unique=False)
    op.create_index(op.f('ix_sales_orders_date'), 'sales_orders', ['date'], unique=False)
    op.create_index(op.f('ix_sales_orders_id'), 'sales_orders', ['id'], unique=False)
    op.create_index(op.f('ix_sales_orders_order_no'), 'sales_orders', ['order_no'], unique=False)
    op.create_index(op.f('ix_sales_orders_product_code'), 'sales_orders', ['product_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_orders_product_code'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_no'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_date'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_customer_name'), table_name='sales_orders')
    op.drop_table('sales_orders')
    # ### end Alembic commands ###
