"""add catalog models

Revision ID: cac1dfcd6f83
Revises: 1c335a1f6a70
Create Date: 2026-06-21 13:18:41.865636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac1dfcd6f83'
down_revision: Union[str, Sequence[str], None] = '1c335a1f6a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(), nullable=False),
    sa.Column('drive_folder_id', sa.String(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_folders_drive_folder_id'), 'catalog_folders', ['drive_folder_id'], unique=True)
    op.create_index(op.f('ix_catalog_folders_folder_name'), 'catalog_folders', ['folder_name'], unique=False)
    op.create_index(op.f('ix_catalog_folders_id'), 'catalog_folders', ['id'], unique=False)
    op.create_table('catalog_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['catalog_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_images_id'), 'catalog_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_images_id'), table_name='catalog_images')
    op.drop_table('catalog_images')
    op.drop_index(op.f('ix_catalog_folders_id'), table_name='catalog_folders')
    op.drop_index(op.f('ix_catalog_folders_folder_name'), table_name='catalog_folders')
    op.drop_index(op.f('ix_catalog_folders_drive_folder_id'), table_name='catalog_folders')
    op.drop_table('catalog_folders')
    # ### end Alembic commands ###
