"""Add catalog cache and sync logs

Revision ID: d7e775a39528
Revises: cac1dfcd6f83
Create Date: 2026-06-21 16:03:05.907291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e775a39528'
down_revision: Union[str, Sequence[str], None] = 'cac1dfcd6f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('folders_synced', sa.Integer(), nullable=True),
    sa.Column('images_processed', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_sync_logs_id'), 'catalog_sync_logs', ['id'], unique=False)
    op.add_column('catalog_folders', sa.Column('cache_status', sa.Boolean(), nullable=True))
    op.add_column('catalog_images', sa.Column('drive_file_id', sa.String(), nullable=True))
    op.add_column('catalog_images', sa.Column('thumbnail_150', sa.String(), nullable=True))
    op.add_column('catalog_images', sa.Column('thumbnail_300', sa.String(), nullable=True))
    op.add_column('catalog_images', sa.Column('thumbnail_600', sa.String(), nullable=True))
    op.add_column('catalog_images', sa.Column('cache_status', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_catalog_images_drive_file_id'), 'catalog_images', ['drive_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_images_drive_file_id'), table_name='catalog_images')
    op.drop_column('catalog_images', 'cache_status')
    op.drop_column('catalog_images', 'thumbnail_600')
    op.drop_column('catalog_images', 'thumbnail_300')
    op.drop_column('catalog_images', 'thumbnail_150')
    op.drop_column('catalog_images', 'drive_file_id')
    op.drop_column('catalog_folders', 'cache_status')
    op.drop_index(op.f('ix_catalog_sync_logs_id'), table_name='catalog_sync_logs')
    op.drop_table('catalog_sync_logs')
    # ### end Alembic commands ###
